# Generated by Django 2.1.11 on 2019-08-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
